# Generated by Django 3.1.7 on 2021-07-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='visit/%Y/%m/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='visit/%Y/%m/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='visit/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='visit/map/%Y/%m/')),
                ('map_description', models.TextField(blank=True)),
                ('city', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id',)},
            },
        ),
    ]
