# Generated by Django 3.1.7 on 2021-07-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='visit/1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='visit/2/%Y/%m/'),
        ),
    ]
