# Generated by Django 3.1.7 on 2021-04-13 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='blogs',
        ),
    ]
