# Generated by Django 3.1.7 on 2021-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210413_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='blogs',
            name='content2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='content3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='content4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
