# Generated by Django 3.1.7 on 2021-07-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210713_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content4',
            field=models.TextField(null=True),
        ),
    ]
