# Generated by Django 3.1.7 on 2021-07-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210409_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extraimage1',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product',
            name='extraimage2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product',
            name='extraimage3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
