# Generated by Django 3.2 on 2021-10-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extraimage1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extraimage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extraimage3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
